# Generated by Django 3.1.2 on 2020-10-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catholique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
