# Generated by Django 3.1.2 on 2020-10-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catholique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='none',
            field=models.CharField(max_length=20),
        ),
    ]
