# Generated by Django 3.1.2 on 2020-10-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catholique', '0002_auto_20201019_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personel',
            old_name='id_no',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='personel',
            old_name='photocopy_id',
            new_name='photocopy_id_image',
        ),
        migrations.AlterField(
            model_name='personel',
            name='father_date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='mother_date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
